// <auto-generated />
using System;
using HSourcer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HSourcer.Persistence.Migrations
{
    [DbContext(typeof(HSourcerDbContext))]
    [Migration("20190510102806_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HSourcer.Domain.Entities.Absence", b =>
                {
                    b.Property<int>("AbsenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AbsenceID")
                        .HasMaxLength(20)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasMaxLength(255);

                    b.Property<int>("ContactPersonId");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DecisionDate");

                    b.Property<DateTime>("EndDate");

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("Status");

                    b.Property<int?>("TeamLeaderId");

                    b.Property<int>("TypeId");

                    b.Property<int>("UserId");

                    b.HasKey("AbsenceId")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("ContactPersonId");

                    b.HasIndex("EndDate");

                    b.HasIndex("StartDate");

                    b.HasIndex("TeamLeaderId");

                    b.HasIndex("UserId");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("HSourcer.Domain.Entities.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OrganizationID")
                        .HasMaxLength(20)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.HasKey("OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("HSourcer.Domain.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TeamID")
                        .HasMaxLength(20)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.Property<int>("OrganizationId");

                    b.HasKey("TeamId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("TeamId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("HSourcer.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserID")
                        .HasMaxLength(20)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<int>("CreatedByUserId");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DeactivationDate");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("OrganizationId");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("PhotoPath");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("Role");

                    b.Property<int>("TeamId");

                    b.HasKey("UserId")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HSourcer.Domain.Entities.Absence", b =>
                {
                    b.HasOne("HSourcer.Domain.Entities.User", "ContactPerson")
                        .WithMany("AbsencesContactPerson")
                        .HasForeignKey("ContactPersonId")
                        .HasConstraintName("FK_Absences_ContactPerson")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HSourcer.Domain.Entities.User", "TeamLeader")
                        .WithMany("AbsencesTeamLeader")
                        .HasForeignKey("TeamLeaderId")
                        .HasConstraintName("FK_Absences_TeamLeaders")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HSourcer.Domain.Entities.User", "User")
                        .WithMany("Absences")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Absences_Users")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HSourcer.Domain.Entities.Team", b =>
                {
                    b.HasOne("HSourcer.Domain.Entities.Organization", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_Teams_Organizations")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HSourcer.Domain.Entities.User", b =>
                {
                    b.HasOne("HSourcer.Domain.Entities.User", "CreatedBy")
                        .WithMany("UsersCreatedBy")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK_Users_UsersCreator")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HSourcer.Domain.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_Users_Organizations")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HSourcer.Domain.Entities.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK_Users_Teams")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
